version: "3"

services:
  logger:
    image: busybox
    command:
    - /bin/sh
    - -c
    - >
      while true;
      do
        echo "[`date`] DEBUG blablablablablablablablablablablablablablabla" >> /logs/date.log;
        sleep 1;
      done
    volumes:
    - logs:/logs

  logrotate:
    build: "."
    environment:
      CRON_SCHEDULE: '* * * * *'
      LOGROTATE_SIZE: 5k
    volumes:
    - logs:/logs

volumes:
  logs:
